language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq valgrind
os:
  - linux

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make && make test
  - valgrind --error-exitcode=42 --leak-check=full --tool=memcheck ./TestRealisations "Test_Files/test3.txt"
  
after_script:
  - make clean

